#!/usr/bin/env bash
# Test Build
git checkout en
npm run-script build
rm -rf build/
git checkout master
npm run-script build

REV_ZH=`git describe --always`

rm -rf _public
git clone git@github.com:g0v/power --depth 1 -b production _public
cd _public
git rm -rf *
cp -R ../build/ ./
cd ..

git checkout en
npm run-script build
REV_EN=`git describe --always`
cp -R build _public/en/

cd _public
git add * 
git commit -m "regen for zh( $REV_ZH ) and en( $REV_EN )"
git push
cd ..
echo "Finished."
